### ISSUE TITLE
GUI Back and Forth Between Displays

### ISSUE THREAD

**Issue by xzener** [Ghawken/FrontView#12]
FV+ v1.164 is unusable for me. The GUI is swapping back and forth between displays. Luckily I can fumble through the settings, but I cant find a single setting that stops this from occurring. May have been caused by the new "Display" feature where the display can be chosen for FV+ to default on.

**Comment by xzener** [comment]
Installed v1.162... Same issue.

**Comment by xzener** [comment]
Hmmm... Its not FV+. Went all the way back to v1.159... Same issue. Rebooted my PC, no change. What the heck happened to my setup?? Any help would be much appreciated.

**Comment by Ghawken** [comment]
Sorry missed this.
The FrontView installer probably is set (and will look and change) to only overwrite files of newer.  So reinstalling may not work - pay to rename directory, and delete and reinstall
But think you have figured it out

It was FV+ - new display setting issue - think it likely didn't overwrite (the settings screen in FV show the version you are running ). Or the log whatever is easier
