### ISSUE TITLE
Wunderground API

### ISSUE THREAD

**Issue by trainerw** [Ghawken/FrontView#14]
It looks like, if I'm not mistaken, that Wunderground is not supplying free API any longer.  How can we get Frontview Weather to work without it?  Can we use a different API system?  Please respond.

**Comment by Ghawken** [comment]
Your right, Wunderground has or is removing API access.  There is a lot of discussion regarding.
Basically front view weather won’t work.
I’ll need to look at another API - probably dark sky - but no ETA for me to do this.

**Comment by Ghawken** [comment]
Changed to DarkSky.Net API in 1.285
Closed

**Comment by trainerw** [comment]
Thank you for all your efforts.  Will you be putting the master 1.285 into a setup application?

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by Ghawken** [comment]
Already there, in usual spot

https://github.com/Ghawken/FrontView/releases

**Comment by trainerw** [comment]
OOOOPS!  Thank you.

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by Ghawken** [comment]
No problem.
Let me know how you go ...

**Comment by trainerw** [comment]
Thank you for your patience and good work.  I installed the update and haven’t setup the weather yet, but still having issues with the fanart.  It used to be when I would go into Kodi to watch a movie or tv show, when the show started the fanart of that show would appear on my lcd along with the time slider.  Since I formatted my hard drive and reloaded everything, I’ve lost that feature.  The screen will remain on the Frontview home screen.  The Frontview plugin is active in Kodi, and Frontview recognizes its connected to Kodi, but when I do a verify its says Bad Remote.  I also have Fanart and Fanart on server checked in settings.  All of my settings seem to be correct.  Any ideas?

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by Ghawken** [comment]
Thank you for your patience and good work.  I installed the update and haven’t setup the weather yet, but still having issues with the fanart.  It used to be when I would go into Kodi to watch a movie or tv show, when the show started the fanart of that show would appear on my lcd along with the time slider.  Since I formatted my hard drive and reloaded everything, I’ve lost that feature.  The screen will remain on the Frontview home screen.  The Frontview plugin is active in Kodi, and Frontview recognizes its connected to Kodi, but when I do a verify its says Bad Remote.  I also have Fanart and Fanart on server checked in settings.  All of my settings seem to be correct.  Any ideas?

Re: above

Okay - what you are referring to is the ‘NowPlaying’ screen fan art.

Without a remote connected essentially nothing will work.  You have with reformatting likely changed your kodi remote connection settings.  When it says Bad remote - it is essentially not connecting ?wrong IP, ?wrong Port, password or different to Kodi settings.

You need to setup your remote connection within Kodi and Frontview (see very old manual with front view - this bit hasn’t changed).  Once remote verified and working should be fine.



Glenn

**Comment by Ghawken** [comment]
Okay
I have tidied up the Remote connection handling - was not that good at telling you not connected.
Also added Kodi 18 remote connection handler.

Version 1.286 in usual spot - releases

Probably pay to keep this github issue closed and just post in the Kodi thread?
https://forum.kodi.tv/showthread.php?tid=259087&pid=2755087#pid2755087

Glenn

**Comment by trainerw** [comment]
I know it needs to be setup, but it just won’t let me even though I know the settings are correct.  I’ve set it up many times before.  I’m enclosing some pics.  Maybe you can see something I’m not.

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by Ghawken** [comment]
Welcome to post in the forum whatever you think would be helpful.

A frontview+log with debug and trace enabled from startup to trying to connect remote would be ideal.
It’s in %appdata%/FrontView+/Log directory

I would still presume you have not set up Kodi correctly.

G

**Comment by trainerw** [comment]
Just wanted you to know that I installed the new version and the remote propagated correctly, so all the fanart is working great.  I know that the lcd screen on the htpc is gimmicky, but it’s nice you created an app that makes some use of it.  I’m using the Moneual MonCaso 932 Home Theatre PC Case.  Thanks for all your great work.
Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by trainerw** [comment]
Greetings!  I have this setup strictly to work with Kodi.  My question is, can this also be setup to work with Windows 10 or PowerDVD, or anything else related to Windows that would show up on the LCD screen?  I could never find any additional information other than for Kodi, Emby and Plex.

Thanks.

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>

**Comment by trainerw** [comment]
Good morning.  Using Frontview+ and Dark Sky, everything works great accept I can’t seem to change Celsius to Fahrenheit.  I have the setting set to US but it doesn’t seem to convert.  Any ideas will be greatly appreciated.

Mike Whitty
Michael Learning Group

(248) 705-9306 - Mobile
trainerw@hotmail.com<mailto:trainerw@hotmail.com>

www.mikewhitty.com<http://www.mikewhitty.com/>
www.salestrainingstore.net<http://www.salestrainingstore.net/>
www.salesmeeting.org<http://www.salesmeeting.org/>
www.inetselling.com<http://www.inetselling.com/>
www.salestrainingaudios.com<http://www.salestrainingaudios.com/>
www.autosalestraining.us<http://www.autosalestraining.us/>
www.rvsalestraining.net<http://www.rvsalestraining.net/>
www.motorcyclesalestraining.com<http://www.motorcyclesalestraining.com/>
www.marinesalestraining.com<http://www.marinesalestraining.com/>
www.autosalesmanager.net<http://www.autosalesmanager.net/>
www.rvsalesmanager.net<http://www.rvsalesmanager.net/>
www.motorcyclesalesmanager.com<http://www.motorcyclesalesmanager.com/>
www.marinesalesmanager.com<http://www.marinesalesmanager.com/>
