### ISSUE TITLE
Fanart in Kodi Not Working

### ISSUE THREAD

**Issue by trainerw** [Ghawken/FrontView#15]
Since the weather api doesn't work, I don't get the fanart showing on the lcd as I'm watching the tv show or movie any longer.  I feel like I have the frontview plugin and app setup correctly since I'm using xonfluence skin with a movie file that opens the program, and that comes down like the fanart used to.  Any ideas?

**Comment by Ghawken** [comment]
I would not think that a not working weather API would cause this problem.  But I’ll have a look/test

Did the fanart ever work for this installation?
I can't follow - are you using an external program to play the movie file? - BC in that case that may cause problems.

Do you have any logs?
