### ISSUE TITLE
Temperature units not changing

### ISSUE THREAD

**Issue by kusco123** [Ghawken/FrontView#17]
The temparture units stay US regardless what setting you choose. Probably only F/C would be sufficient?

**Comment by Ghawken** [comment]
Hi

Mine are non US, and are reported in Celsius - so is possible!

Would suggest correct Long/Lat & auto for weather units, and may take until next weather download/update to update the date.

From darksky:

```
units=[units] optional
Return weather conditions in the requested units. [units] should be one of the following:

auto: automatically select units based on geographic location
ca: same as si, except that windSpeed and windGust are in kilometers per hour
uk2: same as si, except that nearestStormDistance and visibility are in miles, and windSpeed and windGust in miles per hour
us: Imperial units (the default)
si: SI units
```


Give that a try and i’ll have a look a weather code when can.

**Comment by kusco123** [comment]
After a reboot the units chaged to the selected ones - so no issue here! THX!
