### ISSUE TITLE
Feature request - display weather Slides

### ISSUE THREAD

**Issue by kusco123** [Ghawken/FrontView#18]
I would like to suggest to add an option to display instead of the standard picture a picture fitting to the current weather (for example like these http://getwallpapers.com/collection/live-weather-wallpaper-for-desktop)

**Comment by Ghawken** [comment]
Already does this.....

See here:
https://github.com/Ghawken/FrontView/releases/tag/1.211

Good large collection of images, welcome to add own images to folders.

Numbers corresponding to conditions - should be obvious what but based on Kodi weather Fanart conditions: list here:
https://forum.kodi.tv/showthread.php?tid=62261&pid=443186#pid443186

**Comment by kusco123** [comment]
:) - THX
