### ISSUE TITLE
FV+ opens "zoomed" in

### ISSUE THREAD

**Issue by hoogends** [Ghawken/FrontView#22]
I use FV+ (1.315) on a Zalman HD160XT PLUS, Windows 10, screen resolution touchscreen 1024x768
![Zalman HD160XT small](https://user-images.githubusercontent.com/79939963/109710594-22926200-7b9e-11eb-8aac-6c82dd94db59.jpg)

When FV+ is started, the screen is zoomed in. 
![zoomed](https://user-images.githubusercontent.com/79939963/109709393-b7945b80-7b9c-11eb-92c7-fdda8aa53de2.jpg)
Then i change the resolution, to 800x600, but i choose revert and then it's ok.
![displays](https://user-images.githubusercontent.com/79939963/109709510-e4487300-7b9c-11eb-8406-40b5338fd1c9.jpg)
![resolutionchange](https://user-images.githubusercontent.com/79939963/109709519-e7436380-7b9c-11eb-9d9c-1543fbd89dd3.jpg)
![revert](https://user-images.githubusercontent.com/79939963/109709525-ea3e5400-7b9c-11eb-8935-a2a0916c9234.jpg)
![ok](https://user-images.githubusercontent.com/79939963/109709532-ec081780-7b9c-11eb-970b-72c1339d9525.jpg)

Any clue why this happens ?
I've tried numerous options in config via interface or settings.xml, but to no avail.
I could use above as a workaround, but it would be nice if it's correct from starting up.
It's a great replacement for Imon, because that stopped working correctly after latest Windows 10 update.

Regards

**Comment by Ghawken** [comment]
Odd.

Have you changed the screen resolution from within frontview settings?
That is where you should change it for the setting to stick.
Also try ‘force screen resolution’ checkbox checked ‘ unchecked.

failing that:
would try manually edited the settings.XML file - in

%appdata%
/Frontview+

Set the screen resolution to what you ideally wish - for some reason seems to be reading wrong on start.

Glenn

**Comment by hoogends** [comment]
Hi Glenn,

 

That’s jus the thing.

I did change that to 1024x768 in settings.xml.

But doesn’t make any difference, behaviour stays the same……

 

Regards,

hoogends

 

Van: Ghawken <notifications@github.com> 
Verzonden: donderdag 4 maart 2021 22:46
Aan: Ghawken/FrontView <FrontView@noreply.github.com>
CC: hoogends <hoogends@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Ghawken/FrontView] FV+ opens "zoomed" in (#22)

 

Odd.

would try manually edited the settings.XML file - in

%appdata%
Frontview+

Set the screen resolution to what you ideally wish - for some reason seems to be reading wrong on start.

Glenn

**Comment by hoogends** [comment]
Finally got it to work.
I entered the resolution in the wrong section in settings.xml

i thought here: 
ForceResolution>false</ForceResolution
ScreenPositionX>0</ScreenPositionX
ScreenPositionY>0</ScreenPositionY

but this worked: (Resolution section)
DMPelsWidth>1024</DMPelsWidth
DMPelsHeight>768</DMPelsHeight

It's now ok
cheers,
