### ISSUE TITLE
Movie Year

### ISSUE THREAD

**Issue by Ferl67** [Ghawken/FrontView#23]
Hello! Thank you SO MUCH for the awesome Frontview+. Exactly what I was looking for. :)
Is there any way to display the year next to the title? i.e.  Dracula (1931)
Is this an option you could implement or is there a way I can do it by modifying an xml file?

**Comment by Ghawken** [comment]
Thanks for the suggestion

Unfortunately this isn't really possible - the XML file editing doesn't allow that sort of change.  To enable would have to be fairly big code changes and then add user-interface to select or otherwise.
