### ISSUE TITLE
Kodi 20

### ISSUE THREAD

**Issue by Cobramk81** [Ghawken/FrontView#29]
Can you bring Frontview to kodi 20 please?

that Little toy makes so much Fun

**Comment by Ghawken** [comment]
I’ll have a look and see what has changed.  Might take a week or 2 ….

**Comment by Ghawken** [comment]
I should have asked this before I spent the time, forking, replicating the remote for 20, and creating new database etc,.etc.

But what is the issue you are seeing?

Currently using Kodi 19 remote connection (and once have enabled remote control in Kodi) with Kodi 20.

Seems to work fine?  (not reported major changes)

Now playing info screens - Icon Art works..

**Comment by Ghawken** [comment]
See release 1.335

**Comment by Cobramk81** [comment]
Thanks to you that Frontview works so great, bit is there a way to sort the libary alphabeticaly? I use Kodi with eht Emby Addon and in Kodi is everything correct listed but in Frontview the Movies and TV Series are unsorted. Maybe you can help me out

**Comment by Ghawken** [comment]
Go to Settings Library
& 
Disable/Uncheck/Turn off Sort Movies and TV Shows by Date
