### ISSUE TITLE
Emby Stop Button

### ISSUE THREAD

**Issue by xzener** [Ghawken/FrontView#3]
Glenn,

With v1.159, the stop button is not working in Emby Theater.

**Comment by xzener** [comment]
I restarted VF+, seems to be working now.

**Comment by Ghawken** [comment]
Remote checks are run at startup and repeatedly if null or no return from client

If client isn't running when started and press button (at worse will very occ require two button presses)

Sometimes emby seems to send a client doesn't support remote command when it clear should and has in the past (?relates to emby startup).  If that happens FV won't ask the server again until a restart of FV

Glenn
