### ISSUE TITLE
Different Size Poster Issue

### ISSUE THREAD

**Issue by xzener** [Ghawken/FrontView#4]
Depending on the size of the cover, it seems VF+ is displaying some ok, and others not so well...

![capture](https://cloud.githubusercontent.com/assets/3745669/17458651/e636d178-5bcd-11e6-9c4d-a921814e813d.PNG)

Here is the poster to use for troubleshooting...

![poster](https://cloud.githubusercontent.com/assets/3745669/17458653/ff889328-5bcd-11e6-9dd6-cb5f52f94047.jpg)

**Comment by xzener** [comment]
Deleted the Thumbs cache... No change to the problem.

**Comment by xzener** [comment]
Can they not simply overlay that backdrop?

**Comment by Ghawken** [comment]
That's a bit strange.  Did have that issue with some and deleting the thumbnail cache in %appdata% resolved the issue and then when displayed again would have transparency.

You mentioned depending on size - what do you mean?

Have a look in cache directory - presume the cache thumbs do not have transparency - which is the issue.

I'll have a look

Glenn

**Comment by xzener** [comment]
Yes, just looked at the cached thumbs, here is an example of one...

![b1253c9d](https://cloud.githubusercontent.com/assets/3745669/17459161/35fbd46a-5be2-11e6-92cb-150b202f564b.jpg)

**Comment by xzener** [comment]
I thought size had a difference here, but it seems all of them are looking like this.

**Comment by xzener** [comment]
Found the fix. Seems as though if "Optimize cached images to FrontView resolution" is checked, the cover is given the black boarder and not the transparent one. I unchecked it, deleted the cache, and ran a full refresh. Covers now look good.

**Comment by xzener** [comment]
Been checking items by accident quite a bit. Its very easy to do I've noticed.

**Comment by Ghawken** [comment]
Thanks - found and fixed that issue I think.

When FrontView generates its own cache images - it saves as jpg loosing the transparency.

Have changed to png files (they are still named *.jpg - but are png which work fine and less things to change).  Might be larger - but will wait and test some more.

Otherwise checking that will leave as is.

Will close this is a sec after some more testing..

Glenn

**Comment by Ghawken** [comment]
Fixed 1.160
